version: '3.8'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    container_name: Ai_assistant
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:12
    container_name: postgres
    environment:
      POSTGRES_DB: 'your_database_name'
      POSTGRES_USER: 'your_database_user'
      POSTGRES_PASSWORD: 'your_database_password'
    volumes:
      - postgres_data:postgresql/data

volumes:
  postgres_data:
