version: '3.8'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000

    container_name: Ai_assistant
    volumes:
      - .:/Ai_assistant
    ports:
      - 8000:8000
