name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.12.1

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Tests
        run: |
          python manage.py test

      - name: Build Docker image
        run: |
          docker build -t test_image .

      - name: Push Docker image to registry
        uses: docker/build-push-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: your_dockerhub_username/test_image     # Not uploded on docker hub
          tag_with_ref: true

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to AWS Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v17
        with:                                             # These all are SErver configuration
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}                   # I don't have this key if want to test then replace it.
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}               # I don't have this key if want to test then replace it.
          region: your_aws_region
          application_name: your_eb_application_name
          environment_name: your_eb_environment_name
          version_label: ${{ github.sha }}
          source_bundle: your_dockerhub_username/your_image_name:${{ github.sha }}
